# Generated by Django 4.0.6 on 2022-07-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meucep',
            name='complemento',
        ),
    ]
