# Generated by Django 4.0.6 on 2022-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_meucep_bairro_alter_meucep_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meucep',
            name='bairro',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='meucep',
            name='cep',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='meucep',
            name='rua',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
